github.com:
    users:
        h584903:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: h584903
